spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:port/neat_blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: username
    password: password
    druid:
      validation-query: SELECT 1 FROM DUAL
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 6000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

upload:
  target-path: 'D:\\data\\upload'
  path-prefix: /upload

sa-token:
  token-name: satoken
  timeout: 14400
  activity-timeout: -1
  is-concurrent: false
  is-share: true
  is-log: true
  token-style: random-128
  tokenPrefix: Bearer
  private-key: private-key
  public-key: public-key
  init-mail: init-mail
  init-username: init-username
  init-password: init-password

login:
  retry-times: 5